# Generated by Django 4.2.2 on 2024-01-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0002_unit_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='file',
            field=models.FileField(default=0, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
