# Generated by Django 4.2.2 on 2024-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate_app', '0003_userdetails_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='agreement_end_date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
